global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5
  static_map: false
  # rolling_window: true

  origin_x: -10.0
  origin_y: -10.0
  width: 20.0
  height: 20.0
  resolution: 0.11

  # plugins:
  # - {name: obstacles_3d,      type: "costmap_2d::VoxelLayer"}
  # - {name: obstacles_2d,      type: "costmap_2d::ObstacleLayer"}
  # - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
  # - {name: external_costmap,  type: "costmap_2d::StaticLayer"}

  # obstacles_3d:
  #   enabled:                true
  #   # max_obstacle_height:    2.0 
  #   # min_obstacle_height:    0.08
  #   origin_z:               0.0    # meters
  #   z_resolution:           0.2
  #   z_voxels:               10
  #   unknown_threshold:      15     # voxel height
  #   mark_threshold:         0      # voxel height
  #   combination_method:     1      # 1=max, 0=override
  #   track_unknown_space:    true   # default space is unknown
  #   obstacle_range:         3.0    # meters
  #   raytrace_range:         3.5
  #   publish_voxel_map:      true
  #   observation_sources:   depth_camera
  #   depth_camera:
  #     data_type: PointCloud2
  #     topic: /bowser2/bowser2_dc/depth/points
  #     sensor_frame: bowser2/camera_link
  #     marking: true
  #     clearing: true
  #     max_obstacle_height: 2.0
  #     min_obstacle_height: 0.08

  # obstacles_2d:
  #   enabled:                true
  #   origin_z:               0.0    # meters
  #   z_resolution:           0.2
  #   combination_method:     1      # 1=max, 0=override
  #   track_unknown_space:    true   # default space is unknown
  #   obstacle_range:         3.0    # meters
  #   raytrace_range:         3.5
  #   observation_sources: laserscan
  #   laserscan:
  #     data_type: LaserScan
  #     topic: /scan
  #     sensor_frame: bowser2/lidar_link
  #     # expected_update_rate: 0.05 # VERY conservative, actual is ~700Hz
  #     # observation_persistence: 0.0
  #     marking: true
  #     clearing: true
  #     max_obstacle_height: 2.0
  #     min_obstacle_height: 0.08
